version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
